/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package telas;

import DAO.ClienteDAO;
import JPA.ProdutoJPA;
import java.util.List;
import DAO.LancheDAO;
import DAO.PedidoDAO;
import JPA.ClienteJPA;
import JPA.PedidoJPA;
import com.mycompany.projeto_integrador.JPAUtil;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author leand
 */
public class Caixa extends javax.swing.JPanel {

    /**
     * Creates new form CadastroProdutos
     */
    public Caixa() {
        initComponents();

        List<ProdutoJPA> produtos = LancheDAO.Listar(true, true, true);
        for (int i = 0; i < produtos.size(); i++) {
            produtosComboBox.addItem(produtos.get(i).getNome());
        }

        List<ClienteJPA> clientes = ClienteDAO.listar();
        for (int i = 0; i < clientes.size(); i++) {
            ClienteComboBox.addItem(clientes.get(i).getNome());
        }

        JPAUtil jpa = new JPAUtil();
        LocalDate localDate = LocalDate.now();
        dataText.setText(jpa.converterData(localDate.toString()));

        pagamentoComboBox.addItem("Dinheiro");
        pagamentoComboBox.addItem("Pix");
        pagamentoComboBox.addItem("Cartão de crédito");
        pagamentoComboBox.addItem("Cartão de débito");

        quantidadeSpinner.setBackground(Color.white);

        atualizarValorProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        produtosComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        valorText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataText = new javax.swing.JFormattedTextField();
        entregarCheckBox = new javax.swing.JCheckBox();
        ClienteComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        pagamentoComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        quantidadeSpinner = new javax.swing.JSpinner();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("R$ 00,00");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        produtosComboBox.setBackground(new java.awt.Color(255, 255, 255));
        produtosComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        produtosComboBox.setForeground(new java.awt.Color(0, 0, 0));
        produtosComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        produtosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecione o produto");

        valorText.setEditable(false);
        valorText.setBackground(new java.awt.Color(255, 255, 255));
        valorText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        valorText.setForeground(new java.awt.Color(0, 0, 0));
        valorText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Valor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Quantidade");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Data");

        dataText.setBackground(new java.awt.Color(255, 255, 255));
        dataText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dataText.setForeground(new java.awt.Color(0, 0, 0));
        try {
            dataText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataText.setPreferredSize(new java.awt.Dimension(126, 40));

        entregarCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        entregarCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        entregarCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        entregarCheckBox.setText("Para entregar?");

        ClienteComboBox.setBackground(new java.awt.Color(255, 255, 255));
        ClienteComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ClienteComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ClienteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Selecione o nome do cliente");

        pagamentoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        pagamentoComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pagamentoComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pagamentoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagamentoComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Forma de pagamento");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        quantidadeSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantidadeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        quantidadeSpinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        quantidadeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantidadeSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ClienteComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(quantidadeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entregarCheckBox)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(produtosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(322, 322, 322))
                    .addComponent(pagamentoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produtosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorText)
                    .addComponent(dataText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantidadeSpinner))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entregarCheckBox))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(pagamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private void atualizarValorProduto() {
        double valorProduto = 0.0;

        for (ProdutoJPA p : LancheDAO.Listar(true, true, true)) {
            if (p.getNome().equals(produtosComboBox.getSelectedItem().toString())) {
                valorProduto = p.getValor() * (int) quantidadeSpinner.getValue();
                break;
            }
        }
        valorText.setText(String.format("R$ %.2f", valorProduto));
    }
    private void produtosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosComboBoxActionPerformed
        atualizarValorProduto();
    }//GEN-LAST:event_produtosComboBoxActionPerformed

    private void pagamentoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagamentoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagamentoComboBoxActionPerformed

    private void ClienteComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double caixa = 00.00;  
        String valor = valorText.getText().replace("R$", "").replace(",", ".").trim();

        if ((int) quantidadeSpinner.getValue() == 0) {
            JOptionPane.showMessageDialog(null, "Escolha uma quantidade de produto maior que 0!");
        } else if (dataText.getText().matches("\\d{2}/\\d{2}/\\d{4}") && valorText.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            try {
                PedidoJPA pJPA = new PedidoJPA(dataText.getText(), (String) pagamentoComboBox.getSelectedItem(), "Não finalizado", (int) quantidadeSpinner.getValue(),
                        LancheDAO.getId((String) produtosComboBox.getSelectedItem()), ClienteDAO.getId((String) ClienteComboBox.getSelectedItem()), entregarCheckBox.isSelected());

                PedidoDAO pdao = new PedidoDAO();
                caixa += Double.parseDouble(valor);
                jLabel8.setText(String.format("R$ %.2f", caixa));
                pdao.cadastrar(pJPA);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor inválido. Digite um número válido.");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar pedido.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quantidadeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantidadeSpinnerStateChanged
        atualizarValorProduto();
    }//GEN-LAST:event_quantidadeSpinnerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClienteComboBox;
    private javax.swing.JFormattedTextField dataText;
    private javax.swing.JCheckBox entregarCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> pagamentoComboBox;
    private javax.swing.JComboBox<String> produtosComboBox;
    private javax.swing.JSpinner quantidadeSpinner;
    private javax.swing.JTextField valorText;
    // End of variables declaration//GEN-END:variables
}
